
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int cadena = 15;
  public static final int conjunto = 3;
  public static final int especial = 21;
  public static final int cerouno = 8;
  public static final int coma = 12;
  public static final int flecha = 19;
  public static final int porcentaje = 2;
  public static final int or = 5;
  public static final int guion = 9;
  public static final int digito = 16;
  public static final int EOF = 0;
  public static final int letra = 17;
  public static final int id = 20;
  public static final int simbolo = 18;
  public static final int apertura = 11;
  public static final int cierre = 10;
  public static final int positiva = 7;
  public static final int puntocoma = 14;
  public static final int error = 1;
  public static final int concatenacion = 4;
  public static final int dospuntos = 13;
  public static final int kleene = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "porcentaje",
  "conjunto",
  "concatenacion",
  "or",
  "kleene",
  "positiva",
  "cerouno",
  "guion",
  "cierre",
  "apertura",
  "coma",
  "dospuntos",
  "puntocoma",
  "cadena",
  "digito",
  "letra",
  "simbolo",
  "flecha",
  "id",
  "especial"
  };
}

